/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.p2.TRAB2;

import com.p2.TRAB1.normais.Agencia;
import com.p2.TRAB1.normais.Aluno;
import com.p2.TRAB1.normais.Banco;
import com.p2.TRAB1.normais.ContaCorrente;
import com.p2.TRAB1.normais.Coordenador;
import com.p2.TRAB1.normais.Curso;
import com.p2.TRAB1.normais.Diretor;
import com.p2.TRAB1.normais.Disciplina;
import com.p2.TRAB1.normais.Faculdade;
import com.p2.TRAB1.normais.Gerente;
import com.p2.TRAB1.normais.Presidente;
import com.p2.TRAB1.normais.Professor;
import com.p2.TRAB1.normais.SecAcademica;
import com.p2.TRAB1.normais.SecFinanceira;
import java.util.ArrayList;

/**
 *
 * @author Eu2020
 */
public class Menu1 extends javax.swing.JFrame {
    public static ArrayList<Object> pessoas = new ArrayList();
    //Pessoas
    public static ArrayList<ContaCorrente> contas = new ArrayList();
    public static ArrayList<Aluno> alunos = new ArrayList();
    public static ArrayList<Professor> professores = new ArrayList();
    public static ArrayList<Presidente> presidentes = new ArrayList();
    public static ArrayList<Diretor> diretores = new ArrayList();
    public static ArrayList<Coordenador> cordenadores = new ArrayList();
    public static ArrayList<SecAcademica> ACsecretarios = new ArrayList();
    public static ArrayList<SecFinanceira> FNsecretarios = new ArrayList();
    public static ArrayList<Gerente> gerentes = new ArrayList();
    //Faculdades
    public static ArrayList<Faculdade> faculdades = new ArrayList();
    public static ArrayList<Disciplina> disciplinas = new ArrayList();
    public static ArrayList<Curso> cursos = new ArrayList();
    //Bancos
    public static ArrayList<Banco> bancos = new ArrayList();
    public static ArrayList<Agencia> agencias = new ArrayList();
    /**
     * Creates new form Menu1
     */
    public Menu1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        criar_btn = new javax.swing.JButton();
        manipularBTN = new javax.swing.JButton();
        associarBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tela inicial", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        criar_btn.setText("Criar");
        criar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criar_btnActionPerformed(evt);
            }
        });

        manipularBTN.setText("Manipular");
        manipularBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manipularBTNActionPerformed(evt);
            }
        });

        associarBTN.setText("Associar");
        associarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associarBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(associarBTN)
                .addGap(41, 41, 41)
                .addComponent(manipularBTN)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criar_btn)
                    .addComponent(manipularBTN)
                    .addComponent(associarBTN))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void criar_btnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        new Criacao().setVisible(true);
    }                                         

    private void associarBTNActionPerformed(java.awt.event.ActionEvent evt) {                                            
       new Associar().setVisible(true);
    }                                           

    private void manipularBTNActionPerformed(java.awt.event.ActionEvent evt) {                                             
       new Manipular().setVisible(true);
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton associarBTN;
    private javax.swing.JButton criar_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manipularBTN;
    // End of variables declaration                   
}
